import { MedicalRecord } from "../types";

export function createEmptyRecord(): MedicalRecord {
  return {
    patientHeader: {
      fullName: { value: "", confidence: "none" },
      dob: { value: "", confidence: "none" },
      age: { value: "", confidence: "none" },
      gender: { value: "", confidence: "none" },
      mrn: { value: "", confidence: "none" },
      timeOfArrival: { value: "", confidence: "none" },
      dateOfArrival: { value: "", confidence: "none" },
      triageCategory: { value: "", confidence: "none" },
      modeOfArrival: { value: "", confidence: "none" },
      modeOfArrivalOther: { value: "", confidence: "none" },
    },
    personalDetails: {
      residentialAddress: { value: "", confidence: "none" },
      primaryPhone: { value: "", confidence: "none" },
      alternativePhone: { value: "", confidence: "none" },
      emergencyContactName: { value: "", confidence: "none" },
      relationship: { value: "", confidence: "none" },
      emergencyContactPhone: { value: "", confidence: "none" },
      nextOfKinPresent: { value: null, confidence: "none" },
    },
    presentation: {
      chiefComplaint: { value: "", confidence: "none" },
      historyOnset: { value: "", confidence: "none" },
      historyDuration: { value: "", confidence: "none" },
      historySeverity: { value: "", confidence: "none" },
      historyAggravating: { value: "", confidence: "none" },
      allergiesNkda: { value: false, confidence: "none" },
      allergiesList: { value: "", confidence: "none" },
      pastHistory: { value: "", confidence: "none" },
      currentMedications: { value: "", confidence: "none" },
    },
    vitals: {
      timeOfVitals: { value: "", confidence: "none" },
      bpSystolic: { value: "", confidence: "none" },
      bpDiastolic: { value: "", confidence: "none" },
      heartRate: { value: "", confidence: "none" },
      hrRegularity: { value: "", confidence: "none" },
      respiratoryRate: { value: "", confidence: "none" },
      temperature: { value: "", confidence: "none" },
      temperatureRoute: { value: "", confidence: "none" },
      spo2: { value: "", confidence: "none" },
      spo2Mechanism: { value: "", confidence: "none" },
      spo2FlowRate: { value: "", confidence: "none" },
      spo2Device: { value: "", confidence: "none" },
      bloodGlucose: { value: "", confidence: "none" },
      bloodGlucoseUnit: { value: "", confidence: "none" },
      gcsEye: { value: "", confidence: "none" },
      gcsVerbal: { value: "", confidence: "none" },
      gcsMotor: { value: "", confidence: "none" },
      gcsTotal: { value: "", confidence: "none" },
      painScore: { value: "", confidence: "none" },
      examFindingNotes: { value: "", confidence: "none" },
      examFindingsChecked: {
        neuro: false,
        cardio: false,
        resp: false,
        abdo: false,
        musculoskeletal: false,
        skin: false,
      },
    },
    investigations: {
      ecgTime: { value: "", confidence: "none" },
      ecgResult: { value: "", confidence: "none" },
      urinalysisResult: { value: "", confidence: "none" },
      vbgAbgResult: { value: "", confidence: "none" },
      labFbcOrdered: { value: false, confidence: "none" },
      labUeOrdered: { value: false, confidence: "none" },
      labLftOrdered: { value: false, confidence: "none" },
      labCoagsOrdered: { value: false, confidence: "none" },
      labTroponinOrdered: { value: false, confidence: "none" },
      labOther: { value: "", confidence: "none" },
      imgXrayOrdered: { value: false, confidence: "none" },
      imgXrayRegion: { value: "", confidence: "none" },
      imgCtOrdered: { value: false, confidence: "none" },
      imgCtRegion: { value: "", confidence: "none" },
      imgUltrasoundOrdered: { value: false, confidence: "none" },
      imgUltrasoundDetail: { value: "", confidence: "none" },
      imgMriOrdered: { value: false, confidence: "none" },
      imgMriDetail: { value: "", confidence: "none" },
    },
    courseOfAction: {
      workingDiagnosis: { value: "", confidence: "none" },
      immediateInterventions: { value: "", confidence: "none" },
      medications: [],
      referralsSpecialty: { value: "", confidence: "none" },
      referralsTime: { value: "", confidence: "none" },
      referralsContactPerson: { value: "", confidence: "none" },
      disposition: { value: "", confidence: "none" },
      dispositionDetails: { value: "", confidence: "none" },
      followUpTimeline: { value: "", confidence: "none" },
    },
  };
}
